import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Opensea</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1 className="p-8 text-center text-3xl font-bold text-sky-400 underline">
                Opensea
            </h1>
        </div>
    );
};

export default Home;
