import type { NextPage } from "next";
import Head from "next/head";
import { useAddress, useMetamask } from "@thirdweb-dev/react";

const Home: NextPage = () => {
    const connectMetamask = useMetamask();
    const userAddress = useAddress();

    const handelConnect = () => {
        connectMetamask();
    };

    return (
        <div>
            <Head>
                <title>Opensea</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1 className="p-8 text-center text-3xl font-bold text-sky-400 underline">
                Opensea
            </h1>
            <div className="container mx-auto">
                <div className="py-4">
                    <p>User : {userAddress || "undefined"}</p>
                </div>

                <button
                    className="rounded-md border bg-sky-200 py-2 px-4"
                    onClick={handelConnect}
                >
                    Connect MetaMask
                </button>
            </div>
        </div>
    );
};

export default Home;
